# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template for migration file names, e.g. %%(rev)s_%%(slug)s.py
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
# prepend_sys_path = .

# timezone in which to render the date literal within the migration file
# as well as the filename.
# If specified, requires the 'tzdata' package.
# Examples: 'UTC', 'America/New_York'
# timezone =

# revision language used to generate migrations, default is en
# revision_language = en

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to require revision titles prefixed with "REVISION: "
# post_write_hooks =

# comma separated list of package names containing models, e.g. myapp.models
# an optional replacement for target_metadata in env.py
# sqlalchemy.url must be set to connect when using this option
# models_module_prefix =
# sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts. See documentation for details.


# logging configuration: note that this is superseded
# by calls to fileConfig() in env.py.
# The default env.py template assumes logging configuration is decided
# entirely within env.py. If you'd like to configure logging settings
# from this file, comment out the call to fileConfig() in env.py.
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S