"""Cria tabela MidiaOS para uploads

Revision ID: 0ab673c5bb3f
Revises: 31ddfbeb97de
Create Date: 2025-11-02 10:35:03.169515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab673c5bb3f'
down_revision = '31ddfbeb97de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('midia_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_midia', sa.String(length=500), nullable=False),
    sa.Column('tipo_midia', sa.String(length=50), nullable=True),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('midia_os')
    # ### end Alembic commands ###
