"""Remove campos de link fixos da OS

Revision ID: 31ddfbeb97de
Revises: 3c4ecaf48ed8
Create Date: 2025-11-02 10:31:05.678865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ddfbeb97de'
down_revision = '3c4ecaf48ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.drop_column('link_foto_1')
        batch_op.drop_column('link_video')
        batch_op.drop_column('link_foto_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_foto_2', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_video', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_foto_1', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
