"""Adiciona links de midia na OS

Revision ID: 3c4ecaf48ed8
Revises: 509c856af94b
Create Date: 2025-11-02 09:20:37.237502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4ecaf48ed8'
down_revision = '509c856af94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_foto_1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_foto_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_video', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.drop_column('link_video')
        batch_op.drop_column('link_foto_2')
        batch_op.drop_column('link_foto_1')

    # ### end Alembic commands ###
