"""Versao Final com Funcionarios e Carreiras

Revision ID: 509c856af94b
Revises: 
Create Date: 2025-11-01 16:16:14.965549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509c856af94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cargo', sa.String(length=100), nullable=False),
    sa.Column('competencias', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_cargo')
    )
    op.create_table('parceiro_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('eh_cliente', sa.Boolean(), nullable=False),
    sa.Column('eh_fornecedor', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('motivo_inativacao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['carreira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento', sa.String(length=200), nullable=False),
    sa.Column('defeito_reclamado', sa.String(length=500), nullable=False),
    sa.Column('acessorios', sa.String(length=200), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('valor_servico', sa.Float(), nullable=True),
    sa.Column('observacao_final', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro_negocio.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico')
    op.drop_table('funcionario')
    op.drop_table('usuario')
    op.drop_table('parceiro_negocio')
    op.drop_table('carreira')
    # ### end Alembic commands ###
