"""Adiciona colunas ativo e motivo_inativacao ao Cliente

Revision ID: 9db141e64eda
Revises: 
Create Date: 2025-10-22 20:25:40.428456 
(Sua data/hora será diferente)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db141e64eda' # (Este ID TEM que ser o mesmo do nome do arquivo)
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO POR NÓS! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        
        # CORREÇÃO AQUI: Adicionamos server_default='1'
        # '1' é como o SQL entende 'True' (Verdadeiro)
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))
        
        # CORREÇÃO AQUI: Adicionamos server_default=None (só por garantia)
        batch_op.add_column(sa.Column('motivo_inativacao', sa.String(length=200), nullable=True, server_default=None))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('motivo_inativacao')
        batch_op.drop_column('ativo')
    # ### end Alembic commands ###