"""Versao inicial com Parceiro de Negocios

Revision ID: c4456cbb6058
Revises: 
Create Date: 2025-10-30 00:12:06.436155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4456cbb6058'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parceiro_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('eh_cliente', sa.Boolean(), nullable=False),
    sa.Column('eh_fornecedor', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('motivo_inativacao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento', sa.String(length=200), nullable=False),
    sa.Column('defeito_reclamado', sa.String(length=500), nullable=False),
    sa.Column('acessorios', sa.String(length=200), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('valor_servico', sa.Float(), nullable=True),
    sa.Column('observacao_final', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro_negocio.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico')
    op.drop_table('tecnico')
    op.drop_table('parceiro_negocio')
    # ### end Alembic commands ###
