"""empty message

Revision ID: e5269b386b75
Revises: 9db141e64eda
Create Date: 2025-10-23 21:01:08.340725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5269b386b75'
down_revision = '9db141e64eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_servico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('observacao_final', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.drop_column('observacao_final')
        batch_op.drop_column('valor_servico')

    # ### end Alembic commands ###
